"""Report endpoints."""

from typing import List

from fastapi import APIRouter, Depends, status

from app.api.deps import get_report_service
from app.core.security import get_current_user
from app.schemas.common import ApiResponse
from app.schemas.reports import (
    ReportCreateRequest,
    ReportCreateResponse,
    ReportDetail,
    ReportSummary,
)
from app.services.report_service import ReportService

router = APIRouter(prefix="/reports", tags=["Reports"])


@router.get(
    "",
    response_model=ApiResponse[List[ReportSummary]],
    summary="List all reports",
    description="Returns a list of all reports generated by the current user.",
)
async def list_reports(
    current_user: dict = Depends(get_current_user),
    report_service: ReportService = Depends(get_report_service),
):
    data = await report_service.list_reports(current_user)
    return ApiResponse(success=True, message="Reports retrieved", data=data)


@router.get(
    "/{report_id}",
    response_model=ApiResponse[ReportDetail],
    summary="Get a report by ID",
    description="Returns the full details of a specific report.",
)
async def get_report(
    report_id: str,
    current_user: dict = Depends(get_current_user),
    report_service: ReportService = Depends(get_report_service),
):
    data = await report_service.get_report(report_id, current_user)
    return ApiResponse(success=True, message="Report retrieved", data=data)


@router.post(
    "",
    response_model=ApiResponse[ReportCreateResponse],
    status_code=status.HTTP_201_CREATED,
    summary="Generate a new report",
    description="Initiates generation of a new heat analysis report.",
)
async def create_report(
    payload: ReportCreateRequest,
    current_user: dict = Depends(get_current_user),
    report_service: ReportService = Depends(get_report_service),
):
    data = await report_service.create_report(payload.model_dump(), current_user)
    return ApiResponse(
        success=True, message="Report generation initiated", data=data
    )
