"""Mock weather data."""

MOCK_CURRENT_WEATHER = {
    "location": {
        "name": "Chennai",
        "state": "Tamil Nadu",
        "country": "India",
        "lat": 13.0827,
        "lon": 80.2707,
    },
    "temperature": 38.5,
    "feels_like": 44.2,
    "humidity": 65,
    "wind_speed": 12.5,
    "wind_direction": "SW",
    "uv_index": 9.2,
    "air_quality_index": 142,
    "air_quality_label": "Unhealthy for Sensitive Groups",
    "description": "Partly Cloudy",
    "icon": "partly-cloudy",
    "pressure": 1008,
    "visibility": 8.5,
    "dew_point": 28.3,
    "timestamp": "2024-06-15T14:30:00Z",
}

MOCK_FORECAST = [
    {
        "date": "2024-06-16",
        "temp_max": 40.1,
        "temp_min": 29.5,
        "humidity": 60,
        "uv_index": 10.0,
        "wind_speed": 14.0,
        "description": "Hot & Sunny",
        "icon": "sunny",
        "precipitation_chance": 5,
    },
    {
        "date": "2024-06-17",
        "temp_max": 39.3,
        "temp_min": 28.8,
        "humidity": 62,
        "uv_index": 9.5,
        "wind_speed": 10.0,
        "description": "Partly Cloudy",
        "icon": "partly-cloudy",
        "precipitation_chance": 10,
    },
    {
        "date": "2024-06-18",
        "temp_max": 37.8,
        "temp_min": 28.2,
        "humidity": 70,
        "uv_index": 8.0,
        "wind_speed": 16.0,
        "description": "Cloudy with Showers",
        "icon": "cloudy-rain",
        "precipitation_chance": 40,
    },
    {
        "date": "2024-06-19",
        "temp_max": 36.5,
        "temp_min": 27.5,
        "humidity": 75,
        "uv_index": 7.5,
        "wind_speed": 18.0,
        "description": "Thunderstorms Likely",
        "icon": "thunderstorm",
        "precipitation_chance": 65,
    },
    {
        "date": "2024-06-20",
        "temp_max": 38.0,
        "temp_min": 28.0,
        "humidity": 63,
        "uv_index": 9.0,
        "wind_speed": 12.0,
        "description": "Hot & Hazy",
        "icon": "hazy",
        "precipitation_chance": 10,
    },
]
