import type { HeatZone, PointOfInterest } from "@/types";

// Chennai coordinates as center
export const mapCenter: [number, number] = [13.0827, 80.2707];

export const heatZones: HeatZone[] = [
  {
    id: "hz_001",
    name: "T. Nagar Commercial Zone",
    lat: 13.0418,
    lng: 80.2341,
    radius: 800,
    intensity: "extreme",
    temperature: 42,
    description: "Dense commercial area with high vehicle emissions and concrete surfaces. Minimal vegetation cover.",
  },
  {
    id: "hz_002",
    name: "Koyambedu Market Area",
    lat: 13.0727,
    lng: 80.1947,
    radius: 600,
    intensity: "high",
    temperature: 40,
    description: "High traffic hub with large paved market areas. Heat island effect intensified.",
  },
  {
    id: "hz_003",
    name: "Anna Nagar Industrial Corridor",
    lat: 13.0878,
    lng: 80.2101,
    radius: 700,
    intensity: "high",
    temperature: 39,
    description: "Mixed residential and light industrial zone with reduced tree cover.",
  },
  {
    id: "hz_004",
    name: "Tambaram Junction",
    lat: 12.9249,
    lng: 80.1000,
    radius: 500,
    intensity: "moderate",
    temperature: 37,
    description: "Railway junction area. Moderate heat stress from traffic and infrastructure.",
  },
  {
    id: "hz_005",
    name: "Guindy Industrial Estate",
    lat: 13.0067,
    lng: 80.2206,
    radius: 900,
    intensity: "extreme",
    temperature: 43,
    description: "Large industrial cluster with high heat-generating factories and minimal green space.",
  },
  {
    id: "hz_006",
    name: "Perambur Rail Yard",
    lat: 13.1167,
    lng: 80.2481,
    radius: 400,
    intensity: "moderate",
    temperature: 37,
    description: "Rail infrastructure area. Paved surfaces generate localized heat.",
  },
  {
    id: "hz_007",
    name: "Velachery IT Corridor",
    lat: 12.9784,
    lng: 80.2209,
    radius: 650,
    intensity: "high",
    temperature: 39,
    description: "Tech park zone with glass buildings reflecting heat. Moderate green cover.",
  },
];

export const pointsOfInterest: PointOfInterest[] = [
  // Parks & Green Spaces
  {
    id: "poi_001",
    name: "Guindy National Park",
    category: "park",
    lat: 13.0067,
    lng: 80.2284,
    address: "Guindy, Chennai - 600032",
    isOpen: true,
    distance: 3.2,
    description: "Urban wildlife sanctuary. Significantly cooler than surrounding areas.",
  },
  {
    id: "poi_002",
    name: "Semmozhi Poonga Botanical Garden",
    category: "park",
    lat: 13.0573,
    lng: 80.2492,
    address: "Cathedral Road, Chennai - 600086",
    isOpen: true,
    distance: 1.4,
    description: "Well-maintained botanical garden. Dense canopy provides natural cooling.",
  },
  {
    id: "poi_003",
    name: "Elliot's Beach Park",
    category: "park",
    lat: 12.9987,
    lng: 80.2707,
    address: "Besant Nagar, Chennai - 600090",
    isOpen: true,
    distance: 5.8,
    description: "Beachside park with sea breeze. Effective heat relief during evenings.",
  },
  // Hospitals
  {
    id: "poi_004",
    name: "Rajiv Gandhi Government Hospital",
    category: "hospital",
    lat: 13.0854,
    lng: 80.2717,
    address: "Park Town, Chennai - 600003",
    isOpen: true,
    distance: 0.8,
    description: "24/7 emergency services. Heat illness treatment available.",
  },
  {
    id: "poi_005",
    name: "Apollo Hospital Greams Road",
    category: "hospital",
    lat: 13.0588,
    lng: 80.2527,
    address: "Greams Road, Chennai - 600006",
    isOpen: true,
    distance: 2.1,
    description: "Multi-specialty hospital with heat stroke emergency unit.",
  },
  {
    id: "poi_006",
    name: "Government Stanley Medical College Hospital",
    category: "hospital",
    lat: 13.1117,
    lng: 80.2854,
    address: "Stanley, Chennai - 600001",
    isOpen: true,
    distance: 3.4,
    description: "Government hospital. Free heat illness treatment for all.",
  },
  // Cooling Centers
  {
    id: "poi_007",
    name: "Central Railway Station Cooling Zone",
    category: "cooling_center",
    lat: 13.0826,
    lng: 80.2752,
    address: "Park Town, Chennai - 600003",
    isOpen: true,
    distance: 0.6,
    description: "Air-conditioned waiting hall. Open to all during extreme heat.",
  },
  {
    id: "poi_008",
    name: "Spencer Plaza Mall Cooling Center",
    category: "cooling_center",
    lat: 13.0618,
    lng: 80.2624,
    address: "Anna Salai, Chennai - 600002",
    isOpen: true,
    distance: 1.9,
    description: "Designated cool zone on ground floor. Free entry during heat advisories.",
  },
  {
    id: "poi_009",
    name: "Adyar Community Cooling Hub",
    category: "cooling_center",
    lat: 13.0067,
    lng: 80.2556,
    address: "Adyar, Chennai - 600020",
    isOpen: false,
    distance: 4.5,
    description: "Municipal cooling center. Closed on Sundays.",
  },
  // Water Stations
  {
    id: "poi_010",
    name: "T. Nagar Water Kiosk",
    category: "water_station",
    lat: 13.0418,
    lng: 80.2341,
    address: "Usman Road, T. Nagar",
    isOpen: true,
    distance: 3.8,
    description: "Free chilled drinking water. ORS packets available.",
  },
  {
    id: "poi_011",
    name: "Anna Salai Hydration Point",
    category: "water_station",
    lat: 13.0618,
    lng: 80.2530,
    address: "Anna Salai, Chennai - 600006",
    isOpen: true,
    distance: 2.3,
    description: "Municipal water station. Available 6 AM – 8 PM.",
  },
  {
    id: "poi_012",
    name: "Koyambedu Water Station",
    category: "water_station",
    lat: 13.0727,
    lng: 80.1980,
    address: "Koyambedu, Chennai - 600107",
    isOpen: true,
    distance: 6.1,
    description: "Bus stand water station. Free water and electrolyte sachets.",
  },
];
