import type {
  WeatherCondition,
  HourlyData,
  DailyTrend,
  StatCardData,
} from "@/types";

export const currentWeather: WeatherCondition = {
  id: "wc_001",
  timestamp: new Date().toISOString(),
  location: {
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    lat: 13.0827,
    lng: 80.2707,
  },
  temperature: 38,
  feelsLike: 43,
  humidity: 72,
  uvIndex: 9,
  windSpeed: 14,
  windDirection: "NE",
  aqi: 118,
  aqiCategory: "Unhealthy for Sensitive Groups",
  visibility: 6.5,
  dewPoint: 29,
  heatIndex: 47,
  cloudCover: 35,
  pressure: 1004,
  condition: "Partly Cloudy",
  conditionIcon: "⛅",
  riskScore: 78,
  riskLevel: "high",
};

export const hourlyData: HourlyData[] = [
  { hour: "12 AM", temperature: 31, feelsLike: 35, humidity: 78, uvIndex: 0, riskScore: 28 },
  { hour: "1 AM",  temperature: 30, feelsLike: 34, humidity: 80, uvIndex: 0, riskScore: 25 },
  { hour: "2 AM",  temperature: 29, feelsLike: 33, humidity: 82, uvIndex: 0, riskScore: 22 },
  { hour: "3 AM",  temperature: 28, feelsLike: 32, humidity: 84, uvIndex: 0, riskScore: 20 },
  { hour: "4 AM",  temperature: 28, feelsLike: 31, humidity: 85, uvIndex: 0, riskScore: 18 },
  { hour: "5 AM",  temperature: 27, feelsLike: 30, humidity: 86, uvIndex: 0, riskScore: 15 },
  { hour: "6 AM",  temperature: 28, feelsLike: 31, humidity: 84, uvIndex: 1, riskScore: 18 },
  { hour: "7 AM",  temperature: 30, feelsLike: 34, humidity: 81, uvIndex: 2, riskScore: 25 },
  { hour: "8 AM",  temperature: 32, feelsLike: 36, humidity: 78, uvIndex: 4, riskScore: 35 },
  { hour: "9 AM",  temperature: 34, feelsLike: 39, humidity: 76, uvIndex: 6, riskScore: 48 },
  { hour: "10 AM", temperature: 36, feelsLike: 41, humidity: 74, uvIndex: 8, riskScore: 62 },
  { hour: "11 AM", temperature: 37, feelsLike: 42, humidity: 73, uvIndex: 9, riskScore: 70 },
  { hour: "12 PM", temperature: 38, feelsLike: 43, humidity: 72, uvIndex: 9, riskScore: 78 },
  { hour: "1 PM",  temperature: 39, feelsLike: 45, humidity: 71, uvIndex: 10, riskScore: 84 },
  { hour: "2 PM",  temperature: 40, feelsLike: 46, humidity: 70, uvIndex: 10, riskScore: 88 },
  { hour: "3 PM",  temperature: 40, feelsLike: 46, humidity: 70, uvIndex: 9,  riskScore: 86 },
  { hour: "4 PM",  temperature: 39, feelsLike: 44, humidity: 71, uvIndex: 7,  riskScore: 80 },
  { hour: "5 PM",  temperature: 38, feelsLike: 43, humidity: 72, uvIndex: 5,  riskScore: 72 },
  { hour: "6 PM",  temperature: 36, feelsLike: 41, humidity: 74, uvIndex: 3,  riskScore: 60 },
  { hour: "7 PM",  temperature: 35, feelsLike: 39, humidity: 76, uvIndex: 1,  riskScore: 48 },
  { hour: "8 PM",  temperature: 34, feelsLike: 38, humidity: 77, uvIndex: 0,  riskScore: 42 },
  { hour: "9 PM",  temperature: 33, feelsLike: 37, humidity: 79, uvIndex: 0,  riskScore: 36 },
  { hour: "10 PM", temperature: 32, feelsLike: 36, humidity: 80, uvIndex: 0,  riskScore: 32 },
  { hour: "11 PM", temperature: 31, feelsLike: 35, humidity: 81, uvIndex: 0,  riskScore: 28 },
];

export const weeklyTrend: DailyTrend[] = [
  { day: "Mon", date: "Jun 30", maxTemp: 37, minTemp: 27, avgHumidity: 75, maxUV: 8, riskLevel: "moderate", riskScore: 62 },
  { day: "Tue", date: "Jul 1",  maxTemp: 38, minTemp: 28, avgHumidity: 76, maxUV: 9, riskLevel: "high",     riskScore: 72 },
  { day: "Wed", date: "Jul 2",  maxTemp: 39, minTemp: 29, avgHumidity: 74, maxUV: 9, riskLevel: "high",     riskScore: 76 },
  { day: "Thu", date: "Jul 3",  maxTemp: 41, minTemp: 30, avgHumidity: 73, maxUV: 10, riskLevel: "extreme", riskScore: 91 },
  { day: "Fri", date: "Jul 4",  maxTemp: 40, minTemp: 29, avgHumidity: 72, maxUV: 10, riskLevel: "extreme", riskScore: 88 },
  { day: "Sat", date: "Jul 5",  maxTemp: 39, minTemp: 28, avgHumidity: 73, maxUV: 9, riskLevel: "high",     riskScore: 78 },
  { day: "Sun", date: "Jul 6",  maxTemp: 38, minTemp: 28, avgHumidity: 72, maxUV: 9, riskLevel: "high",     riskScore: 74 },
];

export const statCards: StatCardData[] = [
  {
    label: "Temperature",
    value: 38,
    unit: "°C",
    icon: "thermometer",
    trend: "up",
    trendValue: "+3°C from yesterday",
    description: "Dangerously high",
    color: "#ef4444",
  },
  {
    label: "Feels Like",
    value: 43,
    unit: "°C",
    icon: "flame",
    trend: "up",
    trendValue: "+5°C heat index",
    description: "Heat index elevated",
    color: "#f97316",
  },
  {
    label: "Humidity",
    value: 72,
    unit: "%",
    icon: "droplets",
    trend: "stable",
    trendValue: "Normal range",
    description: "High relative humidity",
    color: "#3b82f6",
  },
  {
    label: "UV Index",
    value: 9,
    unit: "",
    icon: "sun",
    trend: "up",
    trendValue: "Very High",
    description: "Protection essential",
    color: "#eab308",
  },
  {
    label: "Wind Speed",
    value: 14,
    unit: "km/h",
    icon: "wind",
    trend: "stable",
    trendValue: "Light breeze",
    description: "Minimal cooling effect",
    color: "#06b6d4",
  },
  {
    label: "Air Quality",
    value: 118,
    unit: "AQI",
    icon: "cloud",
    trend: "down",
    trendValue: "Moderate concern",
    description: "Sensitive groups affected",
    color: "#a855f7",
  },
];
